# Generated by Django 4.2.1 on 2024-04-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insured',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='insured',
            name='phone',
            field=models.CharField(default='', max_length=25),
        ),
    ]
