# Generated by Django 4.2.1 on 2024-04-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pojisteni', '0002_insured_email_insured_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': 'Insurance'},
        ),
        migrations.AlterModelOptions(
            name='insuranceevent',
            options={'verbose_name': 'InsuranceEvent'},
        ),
        migrations.AlterModelOptions(
            name='insured',
            options={'verbose_name': 'Insured'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Statistics'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'UserRole'},
        ),
    ]
